geekshop/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('accounts.urls', namespace='acc')),
    path('about/', flatv.flatpage, {'url': '/about/'}, name='about'),
    path('reset/', include('django.contrib.auth.urls')),
    path('auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

mainapp/urls.py
# -*- coding: utf-8 -*-
# @Author: MOM
# @Date:   2018-09-11 00:24:28
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-23 16:53:06
from django.urls import path

from .views import (BasketDetailView, ContactsListView, OrderRedirectView,
                    PaymentInvoiceView, ProductByCategoryListView,
                    ProductCreateView, ProductDeleteView, ProductDetailView,
                    ProductListView, ProductUpdateView,
                    ProductWithCategoryListView, SelfOrderCreate,
                    SelfOrderDelete, SelfOrderList, SelfOrderRead,
                    SelfOrderSTPRedirectView, SelfOrderUpdate,
                    createPictureView, deletePictureView, serchView)

app_name = 'main'
urlpatterns = [
    path('order/<int:pk>/', OrderRedirectView.as_view(), name='order'),
    path('payment/', PaymentInvoiceView.as_view(), name='payment'),
    path('products/<int:slug>/edit/', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:slug>/del/', ProductDeleteView.as_view(), name='products_delete'),
    path('products/add/', ProductCreateView.as_view(), name='products_add'),
    path('products/<int:slug>/', ProductDetailView.as_view(), name='products_detail'),
    path('products/category/<int:category>/', ProductByCategoryListView.as_view(), name='products_category'),
    path('createpicture/<int:related_obj>', createPictureView.as_view(), name='createPicture'),
    path('deletepicture/<int:pk>/', deletePictureView.as_view(), name='deletePicture'),
    path('serch/products/', serchView.as_view(), name='serch'),
    path('products/', ProductWithCategoryListView.as_view(), name='products'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('basket/', BasketDetailView.as_view(), name='basket'),

    path('create_selforder/', SelfOrderCreate.as_view(), name='self_order_create'),
    path('delete_selforder/<int:pk>/', SelfOrderDelete.as_view(), name='self_order_delete'),
    path('read_selforder/<int:pk>/', SelfOrderRead.as_view(), name='self_order_read'),
    path('update_selforder/<int:pk>/', SelfOrderUpdate.as_view(), name='self_order_update'),
    path('list_selforder/', SelfOrderList.as_view(), name='self_order_list'),
    path('toproc_selforder/<int:pk>/', SelfOrderSTPRedirectView.as_view(), name='self_order_to_proc'),

    path('', ProductListView.as_view(), name='home'),
]

templates/theme0/base.html
{% load static i18n flatpages cache %}
{% get_flatpages as flatpages %}
<!DOCTYPE html>
<html lang="en">
    <head>{% spaceless %}
        <meta charset="UTF-8">
    <title>{% block title %}{% trans "INTERIOR" %}{% endblock title %}</title>{% block extrastyle %}{% endblock extrastyle %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/project.css' %}?v={{VERSION}}">
{% endspaceless %}
</head>
<body>
<div class="container">
    <header class="header padding-site">
        <a href="{% url 'main:home' %}" class="logo header__logo"><img src="{% static 'images/logo.png' %}" alt="{% trans 'logo' %}" class="header__logo-img"></a>
        <nav class="header__menu-group">
            {% include "mainapp/includes/inc-main-menu.html" %}
            <a class="search header__search" href="{% url 'main:serch' %}">
                <img class="header__search-img" src="{% static 'images/search.png' %}">
            </a>
            <a class="basket header__basket" href="{% url 'main:basket' %}"><img class="header__basket-img" src="{% static 'images/basket.png' %}" alt="{% trans 'basket' %}"></a>
        </nav>
    </header>
    {% include "mainapp/includes/inc-messages.html" %}
    <main class="content {{ menu_over }}">
        {% block content %}
        {% endblock content %}
    </main>
    {% block footer %}
        {% cache 120 'footer' %}
        <footer class="footer padding-site">
            <div class="footer__item">
                <div class="footer__contact">
                    <h3 class="footer__h3">{% trans "CONTACT US" %}</h3>
                    <p class="text footer__text footer__contact-text">{% trans "132A Bridge Road Richmond VIC&nbsp;Australia." %}<br><br>
                        {% trans "Talk to&nbsp;us on&nbsp;1300&nbsp;132" %}<br>
                    {% trans "info@interior.com" %}</p>
                </div>
                <div class="footer__info">
                    <h3 class="footer__h3">{% trans "USEFUL INFORMATION" %}</h3>
                    <ul class="info-list footer__info-list">
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "SALES TERMS" %}</a></li>
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "CUSTOMER CARE" %}</a></li>
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "DELIVERY" %}</a></li>
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "ARCHITECT ACCOUNTS" %}</a></li>
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "CAREERS" %}</a></li>
                        <li class="info-list__item"><a class="info-list__link" href="#">{% trans "EXCHANGES &amp;&nbsp;RETURNS" %}</a></li>
                    </ul>
                </div>
                <div class="footer__touch">
                    <h3 class="footer__h3">{% trans "LET&rsquo;S STAY IN&nbsp;TOUCH!" %}</h3>
                    <p class="text footer__touch-text">{% trans "Suscribe to&nbsp;know about our latest news, products and special offers just for suscribers." %}</p>
                    <div class="footer__inbox">
                        <input class="footer__email" type="email" name="email" placeholder="{% trans 'your email address' %}">
                        <a href="#" class="submit footer__submit"><i class="fas fa-paper-plane"></i></a>
                    </div>
                </div>
            </div>
            <div class="footer__item">
                <p class="footer__copy-text">&copy;&nbsp;{% trans "COPYRIGHT" %}&nbsp;&mdash; {% trans "INTERIOR 2016" %}.{% trans "ALL" %}&nbsp;{% trans "RIGHTS RESERVED" %}.</p>
                <div class="footer__social">
                    <a class="footer__social-link" href="https://www.facebook.com" target="_blank"><img src="{% static 'images/facebook.svg' %}" title="Facebook"></a>
                    <a class="footer__social-link" href="https://twitter.com" target="_blank"><img src="{% static 'images/twitter.svg' %}" title="Twitter"></a>
                    <a class="footer__social-link" href="https://plus.google.com" target="_blank"><img src="{% static 'images/google-plus.svg' %}" title="Google+"></a>
                    <a class="footer__social-link" href="https://www.pinterest.com" target="_blank"><img src="{% static 'images/pinterest.svg' %}" title="Pinterest"></a>
                </div>
                <p class="footer__copy-text">{% trans "TERMS &amp;&nbsp;CONDITIONS&nbsp;/ PRIVACY POLICY &amp;&nbsp;COOKIES" %}</p>
            </div>
        </footer>
        {% endcache %}
    {% endblock footer %}
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}?v={{ VERSION }}"></script>
{% block jscripts %}{% endblock jscripts %}
</body>
</html>