geekshop/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('accounts.urls', namespace='acc')),
    path('about/', flatv.flatpage, {'url': '/about/'}, name='about'),
    path('reset/', include('django.contrib.auth.urls')),
    path('auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

mainapp/urls.py
# -*- coding: utf-8 -*-
# @Author: MOM
# @Date:   2018-09-11 00:24:28
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-23 16:53:06
from django.urls import path

from .views import (BasketDetailView, ContactsListView, OrderRedirectView,
                    PaymentInvoiceView, ProductByCategoryListView,
                    ProductCreateView, ProductDeleteView, ProductDetailView,
                    ProductListView, ProductUpdateView,
                    ProductWithCategoryListView, SelfOrderCreate,
                    SelfOrderDelete, SelfOrderList, SelfOrderRead,
                    SelfOrderSTPRedirectView, SelfOrderUpdate,
                    createPictureView, deletePictureView, serchView)

app_name = 'main'
urlpatterns = [
    path('order/<int:pk>/', OrderRedirectView.as_view(), name='order'),
    path('payment/', PaymentInvoiceView.as_view(), name='payment'),
    path('products/<int:slug>/edit/', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:slug>/del/', ProductDeleteView.as_view(), name='products_delete'),
    path('products/add/', ProductCreateView.as_view(), name='products_add'),
    path('products/<int:slug>/', ProductDetailView.as_view(), name='products_detail'),
    path('products/category/<int:category>/', ProductByCategoryListView.as_view(), name='products_category'),
    path('createpicture/<int:related_obj>', createPictureView.as_view(), name='createPicture'),
    path('deletepicture/<int:pk>/', deletePictureView.as_view(), name='deletePicture'),
    path('serch/products/', serchView.as_view(), name='serch'),
    path('products/', ProductWithCategoryListView.as_view(), name='products'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('basket/', BasketDetailView.as_view(), name='basket'),

    path('create_selforder/', SelfOrderCreate.as_view(), name='self_order_create'),
    path('delete_selforder/<int:pk>/', SelfOrderDelete.as_view(), name='self_order_delete'),
    path('read_selforder/<int:pk>/', SelfOrderRead.as_view(), name='self_order_read'),
    path('update_selforder/<int:pk>/', SelfOrderUpdate.as_view(), name='self_order_update'),
    path('list_selforder/', SelfOrderList.as_view(), name='self_order_list'),
    path('toproc_selforder/<int:pk>/', SelfOrderSTPRedirectView.as_view(), name='self_order_to_proc'),

    path('', ProductListView.as_view(), name='home'),
]

mainapp/models.py
from datetime import timedelta

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import F, Sum
from django.db.models.query import QuerySet
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class CoreQuerySet(QuerySet):
    def delete(self):
        return super().update(active=False)

    def hard_delete(self):
        return super().delete()


class CoreManager(models.Manager):
    def get_queryset(self):
        return CoreQuerySet(self.model).filter(active=True).order_by('sort')

    def hard_delete(self):
        return self.get_queryset().hard_delete()


class Core(models.Model):
    """Ядро для моделей"""

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    description = models.TextField(_('description'), null=True, blank=True, default='')
    sort = models.IntegerField(_(u'sort'), default=0, blank=True, null=True)
    active = models.BooleanField(_(u'active'), default=True, db_index=True)

    all_objects = models.Manager()
    objects = CoreManager()

    def __str__(self):
        return f'{self.title}'

    def delete(self):
        self.active = False
        self.save()

    def hard_delete(self):
        super().delete()


class Picture(Core):
    """Картинки для объектов"""

    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image = models.ImageField(upload_to='images')
    related_obj = models.ForeignKey(Core, verbose_name=_('pictures'), null=True, blank=True, related_name='pictures', on_delete=models.CASCADE)


class ProductCategory(Core):
    """Категории товара"""

    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')
        ordering = ('sort',)

    def save(self, *args, **kwargs):
        if self.id:
            old = type(self).all_objects.get(pk=self.id)
            if old.active != self.active:
                self.product_set.update(active=self.active)
        super().save(*args, **kwargs)


class MakerProduct(Core):
    """Производитель продукции"""

    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')
        ordering = ('sort',)


class Product(Core):
    """Товары/Продукты"""

    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        ordering = ('sort',)

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    code = models.CharField(max_length=6, default='', blank=True, null=False)
    maker = models.ForeignKey(MakerProduct, null=True, on_delete=models.SET_NULL)

    @property
    def rest_quant(self):
        return self.whcard.rest_quant()


class Contacts(models.Model):
    """Контыкты"""

    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{10,12}$', message="Phone number must be entered in the format:" + " '+79995554433'. Up to 12 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=70, blank=True, null=True)
    addres = models.CharField(max_length=80)


class TypePriceList(Core):
    """Типы прайс-листов/цен"""

    class Meta:
        verbose_name = _('Тип прайс-листа')
        verbose_name_plural = _('Типы прайс-листов')
        ordering = ('sort',)


class PriceList(models.Model):
    """Цены для продукции"""

    class Meta:
        verbose_name = _('Прайс-лист')
        verbose_name_plural = _('Прайс-листы')

    product = models.ForeignKey(Product, verbose_name=_('pricelist'), related_name='pricelist', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    type_price = models.ForeignKey(TypePriceList, verbose_name=_('type_price'), related_name='type_price', on_delete=models.CASCADE)


class ManagerInvoice(CoreManager):
    def get_last_or_create(self, **kwargs):
        obj = self.get_queryset().filter(**kwargs).order_by('-date').first()
        if not obj:
            obj = self.create(**kwargs)
        return obj


class Invoice(Core):
    """Счета покупателей"""
    FORMING = _('FM')
    SENT_TO_PROCEED = _('STP')
    PROCEEDED = _('PRD')
    PAID = _('PD')
    READY = _('RDY')
    CANCEL = _('CNC')
    DONE = _('DN')

    ORDER_STATUS_CHOICES = (
        (FORMING, _('Формируется')),
        (SENT_TO_PROCEED, _('Отправлен в обработку')),
        (PAID, _('Оплачен')),
        (PROCEEDED, _('Обрабатывается')),
        (READY, _('Готов к выдаче')),
        (CANCEL, _('Отменен')),
        (DONE, _('Выполнен')),
    )

    FINISH_STATE = (DONE, CANCEL)

    class Meta:
        verbose_name = _('Счет')
        verbose_name_plural = _('Счета')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, related_name='invoices', on_delete=models.PROTECT)
    date = models.DateTimeField(verbose_name=_('Дата создания'), auto_now_add=True, blank=True)
    date_modif = models.DateTimeField(verbose_name=_('Дата модификации'), auto_now=True, blank=True)
    status = models.CharField(verbose_name='Статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING, blank=True)
    specification = models.ManyToManyField(Product, through='Specification')

    objects = ManagerInvoice()

    @property
    def total_cost(self):
        return self.spc.total_cost()

    @property
    def total_quant(self):
        return self.spc.total_quant()

    def save(self, **kwargs):
        if self.status in self.FINISH_STATE:
            self.active = False
        super().save(**kwargs)
        if not self.title:
            date = self.date.strftime('%Y-%m-%d')
            self.title = f'№ {self.id} от {date}'
            self.save()


class SpcQuerySet(CoreQuerySet):
    def total_cost(self):
        return self.aggregate(summ=Sum(F('quant') * F('price'), output_field=models.FloatField()))['summ'] or 0.00

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def hard_delete(self):
        for spc in self:
            spc.dspc.delete()
        return super().hard_delete()


class Specification(Core):
    """Спецификация Счета"""

    class Meta:
        verbose_name = _('Спецификация')
        verbose_name_plural = _('Спецификации')

    ware = models.ForeignKey(Product, null=False, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quant = models.PositiveIntegerField(default=0, null=False)
    invioce = models.ForeignKey(Invoice, related_name='spc', null=False, on_delete=models.CASCADE)
    detail_specification = models.ManyToManyField('WhCard', through='DetailSpecification')

    objects = SpcQuerySet.as_manager()

    def __str__(self):
        return f'{self.ware} {self.quant} {self.price}'

    @property
    def cost(self):
        return f'{round(self.quant * self.price, 2)}'

    def make_detail(self):
        delta = self.quant - self.dspc.total_quant()
        if delta > 0:
            for card in WhCard.objects.get_card(self.ware, quant=delta):
                dspc, created = self.dspc.get_or_create(specification=self, whcard=WhCard.objects.get(id=card['id']))
                dspc.quant += card['quant']
                dspc.save()
        elif delta < 0:
            for dcard in reversed(self.dspc.all()):
                q = max([-dcard.quant, delta])
                dcard.quant += q
                dcard.save()
                if dcard.quant == 0:
                    dcard.delete()
                delta -= q
                if delta == 0:
                    break
        return True if self.quant == self.dspc.total_quant() else False

    def save(self, is_remains=True, **kwargs):
        """
        Arguments:
            **kwargs {dict} -- [description]
        """
        if self.price == 0 and len(self.ware.pricelist.all()) > 0:
            self.price = self.ware.pricelist.first().price
        with transaction.atomic():
            super().save(**kwargs)
            if is_remains:
                if not self.make_detail():
                    raise ValueError("save() Not meke detail for quant: %s" % self.quant)


class ModelManagerDetailSpc(QuerySet):

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def delete(self):
        for obj in self:
            obj.delete()
        return super().delete()


class DetailSpecification(models.Model):
    """
    Расшифровка спецификации

    Предназначена для учета партий и доп. параметров спецификации

    Extends:
        models.Model

    Variables:
        specification {[type]} -- [description]
        quant {[type]} -- [description]
        whcard {[type]} -- [description]
    """
    class Meta:
        verbose_name = _('Расшифровка спецификации')
        verbose_name_plural = _('Расшифровки спецификации')

    specification = models.ForeignKey(Specification, related_name='dspc', null=False, on_delete=models.CASCADE)
    quant = models.PositiveIntegerField(default=0, null=False)
    whcard = models.ForeignKey('WhCard', related_name='dspc', on_delete=models.PROTECT)

    objects = ModelManagerDetailSpc.as_manager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_quant = self.quant

    def __str__(self):
        return f'{self.specification.ware} quant:{self.quant} wh:{self.whcard.id}'

    def _change_wh_quant(self, quant):
        if self.whcard:
            self.whcard.quant += quant
            self.whcard.save()

    def delete(self):
        self._change_wh_quant(self.quant)

templates/theme0/mainapp/add-product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock content %}

templates/theme0/mainapp/base_selforder.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="order_container">
        {% block content %}

        {% endblock %}

	</div>
</body>
</html>

templates/theme0/mainapp/contacts_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="main-contact">
        <h1 class="main-contact__title main-products__title">{% trans "Contact Us" %}</h1>
        <section class="locations padding-site main-contact__locations">
            {% for location in object_list %}
                {% include "mainapp/includes/inc-location.html" %}
            {% endfor %}
        </section>
    </div>
{% endblock content %}

templates/theme0/mainapp/invoice_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <div class="basketPage">
        <h1 class="basketPage__title main-products__title">{% trans "Buy from us" %}</h1>
        {% if object.spc.count == 0 %}
            <div class="text basketPage__text marging-section">
                {% trans "You have not ordered anything yet, go ahead :)" %}
            </div>
        {% else %}
            <table class="basketPage__table marging-section padding-site">
                <tr>
                    <th>{% trans '№' %}</th>
                    <th>{% trans 'Product' %}</th>
                    <th>{% trans 'Count' %}</th>
                    <th>{% trans 'Price' %}</th>
                    <th colspan="3">{% trans 'Cost' %}</th>
                </tr>
                {% for spc in object.spc.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'main:products_detail' spc.ware.id %}">{% trans spc.ware.title %}</a></td>
                        <td class="basketPage__table_quant">
                            {% if object.status == object.FORMING and not isread %}
                                <form method="post">{% csrf_token %}
                                        <input type="hidden" name="down" value="{{spc.id}}" />
                                        <button type="submit"><i class="{% if spc.quant > 1 %}fas fa-minus{% endif %}"></i></button>
                                </form>
                            {% endif %}
                            {{spc.quant}}
                            {% if object.status == object.FORMING and not isread %}
                                <form method="post">{% csrf_token %}
                                    <input type="hidden" name="up" value="{{spc.id}}" />
                                    <button type="submit"><i class="{% if spc.ware.rest_quant > 1 %}fas fa-plus{% endif %}"></i></button>
                                </form>
                            {% endif %}
                        </td>
                        <td>{{spc.price|floatformat:2}}</td>
                        <td>{{spc.cost|floatformat:2}}</td>
                        {% if object.status == object.FORMING and not isread %}
                            <td class="bascket_actions_row" >
                                <form action="" method="post">{% csrf_token %}
                                    <input type="hidden" name="del" value="{{spc.id}}" />
                                    <button type="submit"><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="3" >{% trans "Total" %}</td>
                    <td colspan="3" >{{object.total_cost|floatformat:2}}</td>
                </tr>
            </table>
            {% if object.status == object.FORMING and not isread %}
                <div class="basketPage__buy">
                    <form action="{% url 'main:payment' %}" method="post">{% csrf_token %}
                        <input type="hidden" name="pay"/>
                        <input onclick="addNew(this);return false;" type="submit" value="{% trans 'Payment' %}">
                    </form>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock content %}
{% block jscripts %}
    <script type="text/javascript">
    function addNew() {
    var obj = arguments[0];
    var form = obj.closest('form');
    if (form && obj) {
    $.post(form.action, $(form).serialize(), function(data) {
    window.location.reload(true);
    });
    }
    }
    </script>
{% endblock jscripts %}

templates/theme0/mainapp/invoice_list.html
{% extends "mainapp/base_selforder.html" %}
{% load static i18n %}
{% block content %}
    <div class="h2 text-center head">
        {% trans "Yours invoces" %}, {% if user.first_name %}{{ user.first_name|title}}{% else %}{% trans "User" %}{% endif %}
    </div>
    <table class="table orders_list">
        <thead>
            <tr>
                <th>{% trans "ID" %}</th>
                <th>{% trans "Created" %}</th>
                <th>{% trans "Modific" %}</th>
                <th>{% trans "Summ" %}</th>
                <th>{% trans "Status" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                {% if item.active %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.date|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.date_modif|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.total_cost|floatformat }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <form action="{% url 'main:self_order_read' item.pk %}" method="get">
                                <button type="submit" class="btn btn-default btn-xs">
                                {% trans "view" %}
                                </button>
                            </form>
                        </td>
                        <td>
                            {% if item.status == item.FORMING %}
                                <form action="{% url 'main:self_order_update' item.pk %}" method="get">
                                    <button type="submit" class="btn btn-default btn-xs">
                                    {% trans "edit" %}
                                    </button>
                                </form>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == item.FORMING %}
                                <form action="{% url 'main:self_order_delete' item.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-default btn-xs" type="submit" value="item.pk">{% trans "delete" %}</button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
    <a href="{% url 'main:home' %}">
        {% trans "HOME" %}
    </a>
    </button>
    <button class="btn btn-default btn-round">
    <a href="{% url 'main:self_order_create' %}">
        {% trans "New" %}
    </a>
    </button>
{% endblock %}

templates/theme0/mainapp/product_detail.html
{% extends "base.html" %}
{% load static i18n my_tags %}
{% block content %}
    <div class="product-detail">
        {% include "mainapp/includes/inc-product_menu.html" %}
        <div class="product-slider">
            <img class="product-slider__item_full" src="{{ product.pictures.all.0.image.url }}" alt="{% trans 'product-slider' %}">
            <div class="product-slider__switcher">
                {% for img in object.pictures.all %}
                    <a href="#"><img class="product-slider__item{% if img == product.pictures.all.0 %} product-slider__item_active{% endif %}" src="{{ img.image.url }}" alt="{% trans 'controll' %}"></a>
                {% endfor %}
            </div>
        </div>
        <div class="product-info">
            <h1 class="product-info__h1">{% trans object.maker.title %} {% trans object.title %}</h1>
            <h3 class="product-info__h3">{% trans "HOT DEAL" %}</h3>
            <div class="product-info__price">$&nbsp;<span class="product-info__price_num">{% tf price %}</span>/{% trans "sq" %}</div>
            {% include "mainapp/includes/snippets/inc-order.html" with long=1 det=1 prod=object.id %}
            <p class="product-info__text">{% trans object.description|dot_end %}</p>
            {% if request.user.is_staff %}
                <div class="actions-object">
                    <a href="{% url 'main:products_add' %}">{% trans "Add" %}</a>
                    <a href="{% url 'main:products_update' object.id %}">{% trans "Change" %}</a>
                    <a href="{% url 'main:products_delete' object.id %}">{% trans "Delete" %}</a>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="related-product padding-site">
        <div class="related-product__title trending-products__title">
            <h2 class="related-product__h2 trending-products__h2">{% trans "Related Products" %}</h2>
            {% include 'mainapp/includes/snippets/inc-explore-all.html' with extra_class="trending-products__lnk-ghost" %}
        </div>
        <div class="trending-products__products">
            {% for rp in related_products %}
                <div class="trending-products__item">
                    <a href="{% url 'main:products_detail' rp.id %}"><img class="related-product__img" src="{{rp.pictures.all.0.image.url}}" alt="{% trans 'related-product' %}"></a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="marging-section"></div>
{% endblock content %}

templates/theme0/mainapp/product_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <section class="slider padding-site">
        {% include 'mainapp/includes/snippets/inc-slider-info.html' with h3_text="TRENDING" %}
    </section>
    <section class="featured-product padding-site marging-section">
        <div class="tab-control featured-product__item">
            <ul class="tab-control__tabs">
                <li class="tab-control__tabs-item"><a class="tab-control__link {% if new_list == None %}tab-control__tabs_active{% endif %}" href="{% url 'main:home' %}">{% trans "Featured" %}</a></li>
                <li class="tab-control__tabs-item"><a class="tab-control__link {% if new_list %}tab-control__tabs_active{% endif %}" href="{% url 'main:home' %}?new_list=1">{% trans "New" %}</a></li>
            </ul>
            {% include 'mainapp/includes/snippets/inc-explore-all.html' with extra_class="featured-product__lnk-ghost" %}
        </div>
        {% include "mainapp/includes/inc-tab-content.html" %}
    </section>
    {% include "mainapp/includes/snippets/inc-promo-product.html" %}
    <section class="trending-products padding-site">
        <div class="trending-products__title">
            <h2 class="trending-products__h2">{% trans "Trending Products" %}</h2>
            {% include 'mainapp/includes/snippets/inc-explore-all.html' with extra_class="trending-products__lnk-ghost" %}
        </div>
        <div class="trending-products__products">
            {% for pt in popular_list %}
                <article class="trending-products__item">
                    <a class="trending-products__link" href="{% url 'main:products_detail' pt.id %}"><img src="{{pt.pictures.all.0.image.url}}" alt="{% trans 'product-tr' %}"></a>
                </article>
            {% endfor %}
        </div>
    </section>
    <section class="hot-deals slider padding-site marging-section">
        {% include 'mainapp/includes/snippets/inc-slider-info.html' with h3_text="HOT DEAL" ex_cls="hot-deals__info" ex_h3="hot-deals__h3" ex_h2="hot-deals__h2" ex_text="hot-deals__text" ex_btn="hot-deals__button" %}
    </section>
    <section class="exclusive-product padding-site marging-section">
        <article class="exclusive-product__item_lg">
            <img class="exclusive-product__img" src="{% static 'images/exclusiv-img1-lg.jpg' %}" alt="{% trans 'promo-img' %}">
            <div class="exclusive-product__info">
                <h3 class="exclusive-product__h3">{% trans "EXCLUSIVE" %}</h3>
                <h2 class="exclusive-product__h2">{% trans "fishnet chair" %}</h2>
                <p class="text exclusive-product__text">{% blocktrans %}Seat and back with upholstery made of&nbsp;cold cure foam. Steel frame, available in&nbsp;matt{% endblocktrans %}</p>
                {% include "mainapp/includes/snippets/inc-order.html" with long=1 extra_cls="exclusive-product__button" %}
            </div>
        </article>
        <div class="exclusive-product__list">
            {% for obj in object_list|slice:":4" %}
                {% include "mainapp/includes/inc-exclusive-product.html" with excl=obj %}
            {% endfor %}
        </div>
    </section>
    <section class="mobile-app padding-site marging-section">
        <div class="mobile-app__info">
            <h4 class="mobile-app__h4">{% trans "MOBILE APP" %}</h4>
            <h2 class="mobile-app__h2">{% trans "FIND" %}. {% trans "FOLLOW" %}. {% trans "FAVORITE" %}.</h2>
            <p class="mobile-app__text">{% trans "Save your favorites and share your style" %}.</p>
        </div>
        <div class="mobile-app__link-play">
            <a class="mobile-app__apple-store" href='#'><img alt='{% trans "Download on the App Store" %}' src='{% static "images/app-store.jpg" %}' /></a>
            <a class="mobile-app__google-play" href='#'><img alt='{% trans "Get it on Google Play" %}' src='{% static "images/google-play.jpg" %}'/></a>
        </div>
    </section>
{% endblock content %}

templates/theme0/mainapp/products.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="main-products">
        <h1 class="main-products__title">{% trans "Our Products Range" %}</h1>
        {% if serch %}
            <div class="products-menu">
                <form action="" method="post">{% csrf_token %}
                    {{form}}
                    <input type="submit" name="submit" value="Send">
                </form>
            </div>
        {% else %}
            {% include "mainapp/includes/inc-product_menu.html" %}
        {% endif %}
        <div class="trending-products__products padding-site">
            {% for product in object_list %}
                <article class="trending-products__item">
                    {% with product.pictures.all.0.image as img %}
                        <a class="trending-products__link" href="{% url 'main:products_detail' product.id %}"><img src="{{img.url}}" alt="{% trans img.title %}"></a>
                    {% endwith %}
                </article>
            {% endfor %}
        </div>
        {% if is_paginated %}
            <div class="main-products__pagination">
                <span class="main-products__page-links">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'main:products' %}?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
                    {% endif %}
                    <span class="main-products__page-current">
                        {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{% url 'main:products' %}?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
        <a class="main-products__load" href="#"><i class="main-products__iload fas fa-sync-alt"></i></a>
        {% include "mainapp/includes/snippets/inc-promo-product.html" %}
    </div>
{% endblock content %}

templates/theme0/mainapp/serch.html
{% include 'mainapp/products.html' with serch="1" %}