accounts/urls.py
# -*- coding: utf-8 -*-
# @Author: MOM
# @Date:   2018-09-26 20:55:31
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-15 15:11:01
from django.urls import path

from .views import (Login, Logout, Profile, SignUp, SignUpConfirmView,
                    changePassword, changeProfile, createAvatarView,
                    deleteAvatarView)

app_name = 'acc'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('singup/', SignUp.as_view(), name='singup'),
    path('confirm/<uidb64>/<token>/', SignUpConfirmView.as_view(), name='signup_confirm'),
    path('profile/', Profile.as_view(), name='profile'),
    path('editprofile/', changeProfile.as_view(), name='changeProfile'),
    path('editpass/', changePassword.as_view(), name='changePass'),
    path('createavatar/<int:related_obj>', createAvatarView.as_view(), name='createAvatar'),
    path('deleteavatar/<int:pk>/', deleteAvatarView.as_view(), name='deleteAvatar'),
]

geekshop/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('accounts.urls', namespace='acc')),
    path('about/', flatv.flatpage, {'url': '/about/'}, name='about'),
    path('reset/', include('django.contrib.auth.urls')),
    path('auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

mainapp/urls.py
# -*- coding: utf-8 -*-
# @Author: MOM
# @Date:   2018-09-11 00:24:28
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-23 16:53:06
from django.urls import path

from .views import (BasketDetailView, ContactsListView, OrderRedirectView,
                    PaymentInvoiceView, ProductByCategoryListView,
                    ProductCreateView, ProductDeleteView, ProductDetailView,
                    ProductListView, ProductUpdateView,
                    ProductWithCategoryListView, SelfOrderCreate,
                    SelfOrderDelete, SelfOrderList, SelfOrderRead,
                    SelfOrderSTPRedirectView, SelfOrderUpdate,
                    createPictureView, deletePictureView, serchView)

app_name = 'main'
urlpatterns = [
    path('order/<int:pk>/', OrderRedirectView.as_view(), name='order'),
    path('payment/', PaymentInvoiceView.as_view(), name='payment'),
    path('products/<int:slug>/edit/', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:slug>/del/', ProductDeleteView.as_view(), name='products_delete'),
    path('products/add/', ProductCreateView.as_view(), name='products_add'),
    path('products/<int:slug>/', ProductDetailView.as_view(), name='products_detail'),
    path('products/category/<int:category>/', ProductByCategoryListView.as_view(), name='products_category'),
    path('createpicture/<int:related_obj>', createPictureView.as_view(), name='createPicture'),
    path('deletepicture/<int:pk>/', deletePictureView.as_view(), name='deletePicture'),
    path('serch/products/', serchView.as_view(), name='serch'),
    path('products/', ProductWithCategoryListView.as_view(), name='products'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('basket/', BasketDetailView.as_view(), name='basket'),

    path('create_selforder/', SelfOrderCreate.as_view(), name='self_order_create'),
    path('delete_selforder/<int:pk>/', SelfOrderDelete.as_view(), name='self_order_delete'),
    path('read_selforder/<int:pk>/', SelfOrderRead.as_view(), name='self_order_read'),
    path('update_selforder/<int:pk>/', SelfOrderUpdate.as_view(), name='self_order_update'),
    path('list_selforder/', SelfOrderList.as_view(), name='self_order_list'),
    path('toproc_selforder/<int:pk>/', SelfOrderSTPRedirectView.as_view(), name='self_order_to_proc'),

    path('', ProductListView.as_view(), name='home'),
]

accounts/models.py
# -*- coding: utf-8 -*-
# @Author: Max ST
# @Date:   2018-12-09 18:13:14
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-16 17:05:44
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from mainapp.models import Core, Picture


class Theme(Core):
    class Meta:
        verbose_name = _("Тема пользователя")
        verbose_name_plural = _("Темы пользователя")


class User(AbstractUser, Core):
    """
    Пользователи

    Тут они хранятся

    ``Extends``
        :model:`auth.AbstractUser`
        :model:`mainapp.Core`
    """

    user_theme = models.ForeignKey(Theme, null=True, default=90, on_delete=models.SET_NULL, related_name="theme")
    language = models.CharField(_('Language'), max_length=5, blank=True)
    link = models.CharField(_('Link'), max_length=50, blank=True)

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")


class Avatar(Picture):
    """
    Прокси для :model:`mainapp.Picture`

    ``Extends``
        :model:`mainapp.Picture`
    """

    class Meta:
        verbose_name = _("Аватар")
        verbose_name_plural = _("Аватары")
        proxy = True

mainapp/models.py
from datetime import timedelta

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import F, Sum
from django.db.models.query import QuerySet
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class CoreQuerySet(QuerySet):
    def delete(self):
        return super().update(active=False)

    def hard_delete(self):
        return super().delete()


class CoreManager(models.Manager):
    def get_queryset(self):
        return CoreQuerySet(self.model).filter(active=True).order_by('sort')

    def hard_delete(self):
        return self.get_queryset().hard_delete()


class Core(models.Model):
    """Ядро для моделей"""

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    description = models.TextField(_('description'), null=True, blank=True, default='')
    sort = models.IntegerField(_(u'sort'), default=0, blank=True, null=True)
    active = models.BooleanField(_(u'active'), default=True, db_index=True)

    all_objects = models.Manager()
    objects = CoreManager()

    def __str__(self):
        return f'{self.title}'

    def delete(self):
        self.active = False
        self.save()

    def hard_delete(self):
        super().delete()


class Picture(Core):
    """Картинки для объектов"""

    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image = models.ImageField(upload_to='images')
    related_obj = models.ForeignKey(Core, verbose_name=_('pictures'), null=True, blank=True, related_name='pictures', on_delete=models.CASCADE)


class ProductCategory(Core):
    """Категории товара"""

    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')
        ordering = ('sort',)

    def save(self, *args, **kwargs):
        if self.id:
            old = type(self).all_objects.get(pk=self.id)
            if old.active != self.active:
                self.product_set.update(active=self.active)
        super().save(*args, **kwargs)


class MakerProduct(Core):
    """Производитель продукции"""

    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')
        ordering = ('sort',)


class Product(Core):
    """Товары/Продукты"""

    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        ordering = ('sort',)

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    code = models.CharField(max_length=6, default='', blank=True, null=False)
    maker = models.ForeignKey(MakerProduct, null=True, on_delete=models.SET_NULL)

    @property
    def rest_quant(self):
        return self.whcard.rest_quant()


class Contacts(models.Model):
    """Контыкты"""

    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{10,12}$', message="Phone number must be entered in the format:" + " '+79995554433'. Up to 12 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=70, blank=True, null=True)
    addres = models.CharField(max_length=80)


class TypePriceList(Core):
    """Типы прайс-листов/цен"""

    class Meta:
        verbose_name = _('Тип прайс-листа')
        verbose_name_plural = _('Типы прайс-листов')
        ordering = ('sort',)


class PriceList(models.Model):
    """Цены для продукции"""

    class Meta:
        verbose_name = _('Прайс-лист')
        verbose_name_plural = _('Прайс-листы')

    product = models.ForeignKey(Product, verbose_name=_('pricelist'), related_name='pricelist', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    type_price = models.ForeignKey(TypePriceList, verbose_name=_('type_price'), related_name='type_price', on_delete=models.CASCADE)


class ManagerInvoice(CoreManager):
    def get_last_or_create(self, **kwargs):
        obj = self.get_queryset().filter(**kwargs).order_by('-date').first()
        if not obj:
            obj = self.create(**kwargs)
        return obj


class Invoice(Core):
    """Счета покупателей"""
    FORMING = _('FM')
    SENT_TO_PROCEED = _('STP')
    PROCEEDED = _('PRD')
    PAID = _('PD')
    READY = _('RDY')
    CANCEL = _('CNC')
    DONE = _('DN')

    ORDER_STATUS_CHOICES = (
        (FORMING, _('Формируется')),
        (SENT_TO_PROCEED, _('Отправлен в обработку')),
        (PAID, _('Оплачен')),
        (PROCEEDED, _('Обрабатывается')),
        (READY, _('Готов к выдаче')),
        (CANCEL, _('Отменен')),
        (DONE, _('Выполнен')),
    )

    FINISH_STATE = (DONE, CANCEL)

    class Meta:
        verbose_name = _('Счет')
        verbose_name_plural = _('Счета')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, related_name='invoices', on_delete=models.PROTECT)
    date = models.DateTimeField(verbose_name=_('Дата создания'), auto_now_add=True, blank=True)
    date_modif = models.DateTimeField(verbose_name=_('Дата модификации'), auto_now=True, blank=True)
    status = models.CharField(verbose_name='Статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING, blank=True)
    specification = models.ManyToManyField(Product, through='Specification')

    objects = ManagerInvoice()

    @property
    def total_cost(self):
        return self.spc.total_cost()

    @property
    def total_quant(self):
        return self.spc.total_quant()

    def save(self, **kwargs):
        if self.status in self.FINISH_STATE:
            self.active = False
        super().save(**kwargs)
        if not self.title:
            date = self.date.strftime('%Y-%m-%d')
            self.title = f'№ {self.id} от {date}'
            self.save()


class SpcQuerySet(CoreQuerySet):
    def total_cost(self):
        return self.aggregate(summ=Sum(F('quant') * F('price'), output_field=models.FloatField()))['summ'] or 0.00

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def hard_delete(self):
        for spc in self:
            spc.dspc.delete()
        return super().hard_delete()


class Specification(Core):
    """Спецификация Счета"""

    class Meta:
        verbose_name = _('Спецификация')
        verbose_name_plural = _('Спецификации')

    ware = models.ForeignKey(Product, null=False, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quant = models.PositiveIntegerField(default=0, null=False)
    invioce = models.ForeignKey(Invoice, related_name='spc', null=False, on_delete=models.CASCADE)
    detail_specification = models.ManyToManyField('WhCard', through='DetailSpecification')

    objects = SpcQuerySet.as_manager()

    def __str__(self):
        return f'{self.ware} {self.quant} {self.price}'

    @property
    def cost(self):
        return f'{round(self.quant * self.price, 2)}'

    def make_detail(self):
        delta = self.quant - self.dspc.total_quant()
        if delta > 0:
            for card in WhCard.objects.get_card(self.ware, quant=delta):
                dspc, created = self.dspc.get_or_create(specification=self, whcard=WhCard.objects.get(id=card['id']))
                dspc.quant += card['quant']
                dspc.save()
        elif delta < 0:
            for dcard in reversed(self.dspc.all()):
                q = max([-dcard.quant, delta])
                dcard.quant += q
                dcard.save()
                if dcard.quant == 0:
                    dcard.delete()
                delta -= q
                if delta == 0:
                    break
        return True if self.quant == self.dspc.total_quant() else False

    def save(self, is_remains=True, **kwargs):
        """
        Arguments:
            **kwargs {dict} -- [description]
        """
        if self.price == 0 and len(self.ware.pricelist.all()) > 0:
            self.price = self.ware.pricelist.first().price
        with transaction.atomic():
            super().save(**kwargs)
            if is_remains:
                if not self.make_detail():
                    raise ValueError("save() Not meke detail for quant: %s" % self.quant)


class ModelManagerDetailSpc(QuerySet):

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def delete(self):
        for obj in self:
            obj.delete()
        return super().delete()


class DetailSpecification(models.Model):
    """
    Расшифровка спецификации

    Предназначена для учета партий и доп. параметров спецификации

    Extends:
        models.Model

    Variables:
        specification {[type]} -- [description]
        quant {[type]} -- [description]
        whcard {[type]} -- [description]
    """
    class Meta:
        verbose_name = _('Расшифровка спецификации')
        verbose_name_plural = _('Расшифровки спецификации')

    specification = models.ForeignKey(Specification, related_name='dspc', null=False, on_delete=models.CASCADE)
    quant = models.PositiveIntegerField(default=0, null=False)
    whcard = models.ForeignKey('WhCard', related_name='dspc', on_delete=models.PROTECT)

    objects = ModelManagerDetailSpc.as_manager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_quant = self.quant

    def __str__(self):
        return f'{self.specification.ware} quant:{self.quant} wh:{self.whcard.id}'

    def _change_wh_quant(self, quant):
        if self.whcard:
            self.whcard.quant += quant
            self.whcard.save()

    def delete(self):
        self._change_wh_quant(self.quant)

accounts/forms.py
# -*- coding: utf-8 -*-
# @Author: Max ST
# @Date:   2018-12-09 12:28:09
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-15 15:46:47
# from django import forms
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm

from .models import User


class UserRegisterForm(UserCreationForm, PasswordResetForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'description', 'user_theme', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self, commit=True, **kwargs):
        user = self.instance
        if not user.id:
            user.active = False
            user = super(UserRegisterForm, self).save()
            PasswordResetForm.save(self, **kwargs)
        return user


class UserActivationRegisterForm(forms.Form):
    class Meta:
        model = User

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        self.user.active = True
        if commit:
            self.user.save()
        return self.user

templates/theme0/accounts/avatar_confirm_delete.html
{% include "mainapp/product_confirm_delete.html" %}

templates/theme0/accounts/avatar_form.html
{% extends "base.html" %}{% load i18n %}
{% block content %}
    <div class="center marging-section text" style="text-align:center;">
        <form method="post" style="text-align:left;margin:auto;display:inline-block;" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="{% trans 'Save' %}">
        </form>
    </div>
{% endblock content %}

templates/theme0/accounts/change_pass.html
{% extends "base.html" %}{% load i18n %}
{% block content %}
    <div class="authForm marging-section text">
        <form class="authForm__form" method="post" >{% csrf_token %}
            {{form.old_password.label_tag}}
            {{form.old_password}}
            {{form.new_password1.label_tag}}
            {{form.new_password1}}
            {{form.new_password2.label_tag}}
            {{form.new_password2}}
            <input type="submit" value="{% trans 'Save' %}">
        </form>
    </div>
    {{form.old_password.errors}}
    {{form.new_password1.errors}}
    {{form.new_password2.errors}}
{% endblock content %}

templates/theme0/accounts/login.html
{% extends "base.html" %}{% load i18n %}
{% block content %}
    <h1 class="authForm__title main-products__title">{% trans "Buy from us" %}</h1>
    <div class="authForm">
        <form class="authForm__form" method="post" >
            {% csrf_token %}
            {{form}}
            <button type="submit">{% trans 'Log in' %}</button>
            <button class="btn btn-round form-control">
                <a href="{% url "social:begin" "google-oauth2" %}?next=/">{% trans "Google+ sign in" %}</a>
            </button>
        </form>
    </div>
{% endblock content %}

templates/theme0/accounts/password_reset_form.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <p class="marging-section padding-site">{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
    <form method="post">{% csrf_token %}
        <fieldset class="padding-site text">
            <div class="form-row field-email">
                {{ form.email.errors }}
                <label for="id_email">{% trans 'Email address:' %}</label>
                {{ form.email }}
            </div>
            <input type="submit" value="{% trans 'Reset my password' %}">
        </fieldset>
    </form>
{% endblock content %}

templates/theme0/accounts/signup_confirm.html
{% extends "base.html" %}{% load i18n %}
{% block content %}
    <div class="center marging-section text">
    {% if validlink %}
        <p>{% trans "Для подтверждения акаунта нажмите кнопку ниже" %}</p>
        <form method="post">{% csrf_token %}
            <button type="submit">{% trans 'Продолжить' %}</button>
        </form>
    {% else %}
        <p>{% trans "Ссылка для активации недействительна, возможно, потому что она уже использовалась. Пожалуйста, попробуйте еще раз." %}</p>
    {% endif %}
    </div>
{% endblock content %}

templates/theme0/accounts/signup_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Вы получили это письмо для подтверждения регистрации на сайте {{ site_name }}.{% endblocktrans %}
{% trans "Пожалуйста, перейдите на по ссылке для подтверждения регистрации:" %}
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'acc:signup_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Ваше имя пользователя, в том случае если вы забыли:" %} {{ user.get_username }}
{% trans "Спасибо за использование нашего сайта!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

templates/theme0/accounts/user_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <div class="product-detail">
        {% if object %}
            {% include 'accounts/includes/inc-pic_gallery.html' with images=object.pictures.all %}
            <div class="product-info">
                <h1 class="product-info__h1">{% trans user.email %}</h1>
                <h3 class="product-info__h3">{% trans user.last_name %}</h3>
                <div class="product-info__price"><span class="product-info__price_num">{% trans user.first_name %}</span></div>
                <a href="{% url 'acc:changeProfile' %}" class="button button_push button_long">
                    {% trans "Change" %}
                    <img src="{% static 'images/arrow-detail.png' %}" alt="{% trans 'arrow-detail' %}">
                </a>
                <a href="{% url 'acc:changePass' %}" class="button putton_push changePass">{% trans "Change password" %}</a>
                <p class="product-info__text">{% trans user.description %}
                </p>
            </div>
        </div>
    {% endif %}
    <div class="marging-section"></div>
{% endblock content %}

templates/theme0/accounts/user_form.html
{% extends "base.html" %}{% load i18n %}
{% block extrastyle %}<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">{% endblock extrastyle %}
{% block jscripts %}<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>{% endblock jscripts %}
{% block content %}
    <div class="center marging-section text">
        <form action="{% url 'acc:changeProfile' %}" method="post" >
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="{% trans 'Save' %}">
        </form>
        <div class="product-slider__switcher">
            {% include 'accounts/includes/inc-change_pic_gallery.html' with images=object.pictures.all %}
        </div>
    </div>
{% endblock content %}

templates/theme0/accounts/user_signup_form.html
{# {% extends "base.html" %} #}
{% load static i18n %}
{% load flatpages %}
{% get_flatpages as flatpages %}
<!DOCTYPE html>
<html lang="en">
<head>{% spaceless %}
    <meta charset="UTF-8">
    <title>{% trans "Registration" %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/project.css' %}?v={{VERSION}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block extrastyle %}{% endblock extrastyle %}
{% endspaceless %}</head>
<body>
    <div class="container">
        <header class="padding-site">

        </header>
        <main class="content padding-site">
            {% block content %}
                <h1 class="authForm__title main-products__title">{% trans "Registration" %}</h1>
                <div class="authForm">
                    <form class="authForm__form" action="{% url 'acc:singup' %}" method="post" >
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-round form-control">{% trans 'Save' %}</button>
                    </form>
                </div>
            {% endblock content %}
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block jscripts %}{% endblock jscripts %}
</body>
</html>