geekshop/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import views as flatv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('accounts.urls', namespace='acc')),
    path('about/', flatv.flatpage, {'url': '/about/'}, name='about'),
    path('reset/', include('django.contrib.auth.urls')),
    path('auth/verify/google/oauth2/', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

mainapp/urls.py
# -*- coding: utf-8 -*-
# @Author: MOM
# @Date:   2018-09-11 00:24:28
# @Last Modified by:   Max ST
# @Last Modified time: 2018-12-23 16:53:06
from django.urls import path

from .views import (BasketDetailView, ContactsListView, OrderRedirectView,
                    PaymentInvoiceView, ProductByCategoryListView,
                    ProductCreateView, ProductDeleteView, ProductDetailView,
                    ProductListView, ProductUpdateView,
                    ProductWithCategoryListView, SelfOrderCreate,
                    SelfOrderDelete, SelfOrderList, SelfOrderRead,
                    SelfOrderSTPRedirectView, SelfOrderUpdate,
                    createPictureView, deletePictureView, serchView)

app_name = 'main'
urlpatterns = [
    path('order/<int:pk>/', OrderRedirectView.as_view(), name='order'),
    path('payment/', PaymentInvoiceView.as_view(), name='payment'),
    path('products/<int:slug>/edit/', ProductUpdateView.as_view(), name='products_update'),
    path('products/<int:slug>/del/', ProductDeleteView.as_view(), name='products_delete'),
    path('products/add/', ProductCreateView.as_view(), name='products_add'),
    path('products/<int:slug>/', ProductDetailView.as_view(), name='products_detail'),
    path('products/category/<int:category>/', ProductByCategoryListView.as_view(), name='products_category'),
    path('createpicture/<int:related_obj>', createPictureView.as_view(), name='createPicture'),
    path('deletepicture/<int:pk>/', deletePictureView.as_view(), name='deletePicture'),
    path('serch/products/', serchView.as_view(), name='serch'),
    path('products/', ProductWithCategoryListView.as_view(), name='products'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('basket/', BasketDetailView.as_view(), name='basket'),

    path('create_selforder/', SelfOrderCreate.as_view(), name='self_order_create'),
    path('delete_selforder/<int:pk>/', SelfOrderDelete.as_view(), name='self_order_delete'),
    path('read_selforder/<int:pk>/', SelfOrderRead.as_view(), name='self_order_read'),
    path('update_selforder/<int:pk>/', SelfOrderUpdate.as_view(), name='self_order_update'),
    path('list_selforder/', SelfOrderList.as_view(), name='self_order_list'),
    path('toproc_selforder/<int:pk>/', SelfOrderSTPRedirectView.as_view(), name='self_order_to_proc'),

    path('', ProductListView.as_view(), name='home'),
]

mainapp/models.py
from datetime import timedelta

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import F, Sum
from django.db.models.query import QuerySet
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class CoreQuerySet(QuerySet):
    def delete(self):
        return super().update(active=False)

    def hard_delete(self):
        return super().delete()


class CoreManager(models.Manager):
    def get_queryset(self):
        return CoreQuerySet(self.model).filter(active=True).order_by('sort')

    def hard_delete(self):
        return self.get_queryset().hard_delete()


class Core(models.Model):
    """Ядро для моделей"""

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    description = models.TextField(_('description'), null=True, blank=True, default='')
    sort = models.IntegerField(_(u'sort'), default=0, blank=True, null=True)
    active = models.BooleanField(_(u'active'), default=True, db_index=True)

    all_objects = models.Manager()
    objects = CoreManager()

    def __str__(self):
        return f'{self.title}'

    def delete(self):
        self.active = False
        self.save()

    def hard_delete(self):
        super().delete()


class Picture(Core):
    """Картинки для объектов"""

    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image = models.ImageField(upload_to='images')
    related_obj = models.ForeignKey(Core, verbose_name=_('pictures'), null=True, blank=True, related_name='pictures', on_delete=models.CASCADE)


class ProductCategory(Core):
    """Категории товара"""

    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')
        ordering = ('sort',)

    def save(self, *args, **kwargs):
        if self.id:
            old = type(self).all_objects.get(pk=self.id)
            if old.active != self.active:
                self.product_set.update(active=self.active)
        super().save(*args, **kwargs)


class MakerProduct(Core):
    """Производитель продукции"""

    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')
        ordering = ('sort',)


class Product(Core):
    """Товары/Продукты"""

    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        ordering = ('sort',)

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    code = models.CharField(max_length=6, default='', blank=True, null=False)
    maker = models.ForeignKey(MakerProduct, null=True, on_delete=models.SET_NULL)

    @property
    def rest_quant(self):
        return self.whcard.rest_quant()


class Contacts(models.Model):
    """Контыкты"""

    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    title = models.CharField(_('title'), max_length=250, default='', blank=True, null=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{10,12}$', message="Phone number must be entered in the format:" + " '+79995554433'. Up to 12 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    email = models.EmailField(max_length=70, blank=True, null=True)
    addres = models.CharField(max_length=80)


class TypePriceList(Core):
    """Типы прайс-листов/цен"""

    class Meta:
        verbose_name = _('Тип прайс-листа')
        verbose_name_plural = _('Типы прайс-листов')
        ordering = ('sort',)


class PriceList(models.Model):
    """Цены для продукции"""

    class Meta:
        verbose_name = _('Прайс-лист')
        verbose_name_plural = _('Прайс-листы')

    product = models.ForeignKey(Product, verbose_name=_('pricelist'), related_name='pricelist', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    type_price = models.ForeignKey(TypePriceList, verbose_name=_('type_price'), related_name='type_price', on_delete=models.CASCADE)


class ManagerInvoice(CoreManager):
    def get_last_or_create(self, **kwargs):
        obj = self.get_queryset().filter(**kwargs).order_by('-date').first()
        if not obj:
            obj = self.create(**kwargs)
        return obj


class Invoice(Core):
    """Счета покупателей"""
    FORMING = _('FM')
    SENT_TO_PROCEED = _('STP')
    PROCEEDED = _('PRD')
    PAID = _('PD')
    READY = _('RDY')
    CANCEL = _('CNC')
    DONE = _('DN')

    ORDER_STATUS_CHOICES = (
        (FORMING, _('Формируется')),
        (SENT_TO_PROCEED, _('Отправлен в обработку')),
        (PAID, _('Оплачен')),
        (PROCEEDED, _('Обрабатывается')),
        (READY, _('Готов к выдаче')),
        (CANCEL, _('Отменен')),
        (DONE, _('Выполнен')),
    )

    FINISH_STATE = (DONE, CANCEL)

    class Meta:
        verbose_name = _('Счет')
        verbose_name_plural = _('Счета')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, related_name='invoices', on_delete=models.PROTECT)
    date = models.DateTimeField(verbose_name=_('Дата создания'), auto_now_add=True, blank=True)
    date_modif = models.DateTimeField(verbose_name=_('Дата модификации'), auto_now=True, blank=True)
    status = models.CharField(verbose_name='Статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING, blank=True)
    specification = models.ManyToManyField(Product, through='Specification')

    objects = ManagerInvoice()

    @property
    def total_cost(self):
        return self.spc.total_cost()

    @property
    def total_quant(self):
        return self.spc.total_quant()

    def save(self, **kwargs):
        if self.status in self.FINISH_STATE:
            self.active = False
        super().save(**kwargs)
        if not self.title:
            date = self.date.strftime('%Y-%m-%d')
            self.title = f'№ {self.id} от {date}'
            self.save()


class SpcQuerySet(CoreQuerySet):
    def total_cost(self):
        return self.aggregate(summ=Sum(F('quant') * F('price'), output_field=models.FloatField()))['summ'] or 0.00

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def hard_delete(self):
        for spc in self:
            spc.dspc.delete()
        return super().hard_delete()


class Specification(Core):
    """Спецификация Счета"""

    class Meta:
        verbose_name = _('Спецификация')
        verbose_name_plural = _('Спецификации')

    ware = models.ForeignKey(Product, null=False, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quant = models.PositiveIntegerField(default=0, null=False)
    invioce = models.ForeignKey(Invoice, related_name='spc', null=False, on_delete=models.CASCADE)
    detail_specification = models.ManyToManyField('WhCard', through='DetailSpecification')

    objects = SpcQuerySet.as_manager()

    def __str__(self):
        return f'{self.ware} {self.quant} {self.price}'

    @property
    def cost(self):
        return f'{round(self.quant * self.price, 2)}'

    def make_detail(self):
        delta = self.quant - self.dspc.total_quant()
        if delta > 0:
            for card in WhCard.objects.get_card(self.ware, quant=delta):
                dspc, created = self.dspc.get_or_create(specification=self, whcard=WhCard.objects.get(id=card['id']))
                dspc.quant += card['quant']
                dspc.save()
        elif delta < 0:
            for dcard in reversed(self.dspc.all()):
                q = max([-dcard.quant, delta])
                dcard.quant += q
                dcard.save()
                if dcard.quant == 0:
                    dcard.delete()
                delta -= q
                if delta == 0:
                    break
        return True if self.quant == self.dspc.total_quant() else False

    def save(self, is_remains=True, **kwargs):
        """
        Arguments:
            **kwargs {dict} -- [description]
        """
        if self.price == 0 and len(self.ware.pricelist.all()) > 0:
            self.price = self.ware.pricelist.first().price
        with transaction.atomic():
            super().save(**kwargs)
            if is_remains:
                if not self.make_detail():
                    raise ValueError("save() Not meke detail for quant: %s" % self.quant)


class ModelManagerDetailSpc(QuerySet):

    def total_quant(self):
        return self.aggregate(summ=Sum(F('quant'), output_field=models.FloatField()))['summ'] or 0.00

    def delete(self):
        for obj in self:
            obj.delete()
        return super().delete()


class DetailSpecification(models.Model):
    """
    Расшифровка спецификации

    Предназначена для учета партий и доп. параметров спецификации

    Extends:
        models.Model

    Variables:
        specification {[type]} -- [description]
        quant {[type]} -- [description]
        whcard {[type]} -- [description]
    """
    class Meta:
        verbose_name = _('Расшифровка спецификации')
        verbose_name_plural = _('Расшифровки спецификации')

    specification = models.ForeignKey(Specification, related_name='dspc', null=False, on_delete=models.CASCADE)
    quant = models.PositiveIntegerField(default=0, null=False)
    whcard = models.ForeignKey('WhCard', related_name='dspc', on_delete=models.PROTECT)

    objects = ModelManagerDetailSpc.as_manager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_quant = self.quant

    def __str__(self):
        return f'{self.specification.ware} quant:{self.quant} wh:{self.whcard.id}'

    def _change_wh_quant(self, quant):
        if self.whcard:
            self.whcard.quant += quant
            self.whcard.save()

    def delete(self):
        self._change_wh_quant(self.quant)

templates/theme0/mainapp/includes/inc-change_pic_gallery.html
{% load i18n %}
<div class="product-slider">
    {% if images %}
        <div class="product-slider__switcher">
            <div class="block">
                <a href="{% url 'main:createPicture' object.id %}">
                    <div class="text" style="display:block">
                        {% trans 'Add' %}
                    </div>
                </a>
            </div>
            {% for img in images %}
                <div class="info-list text">
                    <img class="product-slider__item" src="{{ img.image.url }}" alt="{% trans 'controll' %}">
                    <a href="{% url 'main:deletePicture' img.id %}">
                        {% trans 'Delete' %}
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>

templates/theme0/mainapp/includes/inc-exclusive-product.html
{% load i18n %}
<article>
    <a href="{% url 'main:products_detail' excl.id %}" class="exclusive-product__item_sm"><img class="exclusive-product__img" src="{{excl.pictures.all.0.image.url}}" alt="{% trans 'exclusiv-img' %}"></a>
</article>

templates/theme0/mainapp/includes/inc-location.html
{% load i18n %}
<div class="locations__location main-contact__location">
    <i class="locations__imap fas fa-map-marker-alt"></i>
    <h3 class="locations__h3">{% trans location.title %}</h3>
    <label class="locations__lblphone" for="locations__phone">{% trans "Phone" %}:</label>
    <div class="locations__phone">{% trans location.phone_number %}</div>
    <label class="locations__lblemail" for="locations__email">{% trans "Email" %}:</label>
    <div class="locations__email">{% trans location.email %}</div>
    <label class="locations__lbladdres" for="locations__addres">{% trans "Address" %}:</label>
    <div class="locations__addres">{% trans location.addres %}</div>
</div>

templates/theme0/mainapp/includes/inc-main-menu.html
{% load i18n %}
<ul class="menu header__menu">
    {% for mm in main_menu %}
            {% if mm.get_url == 'acc:profile' %}
                <li class="menu__item menu__item_prof"><a class="menu__link{% if mm.get_url in curr_path_name %} menu_active{% endif %}" href="{% if mm.get_url == '#' %}#{% else %}{% url mm.get_url %}{% endif %}">{% trans mm.title %}</a>
            {% else %}
                <li class="menu__item"><a class="menu__link{% if mm.get_url in curr_path_name %} menu_active{% endif %}" href="{% if mm.get_url == '#' %}#{% else %}{% url mm.get_url %}{% endif %}">{% trans mm.title %}</a>
            {% endif %}
            <div class="menu__dropprofil">
            {% for mmm in mm.submenu %}
                    <a class="menu__link" href="{% if mmm.get_url == '#' %}#{% else %}{% url mmm.get_url %}{% endif %}">{% trans mmm.title %}</a>
            {% endfor %}
            </div>
            </li>
    {% endfor %}
</ul>

templates/theme0/mainapp/includes/inc-messages.html
{% if messages %}
    <ul class="messages padding-site">
        {% for message in messages %}<li class="{{ message.tags }}">{{ message }}</li>{% endfor %}
    </ul>
{% endif %}

templates/theme0/mainapp/includes/inc-product_menu.html
{% load i18n %}
<ul class="products-menu padding-site">
    <li><a class="products-menu__item {% if curr_path_name == 'main:products' %} products-menu__item_active{% endif %}" href="{% url 'main:products' %}">{% trans "ALL" %}</a></li>
    {% for cat in category %}
        {% url 'main:products_category' cat.id as u %}
        <li><a class="products-menu__item{% if request.path == u %} products-menu__item_active{% endif %}" href="{% url 'main:products_category' cat.id %}">{% trans cat.title %}</a></li>
    {% endfor %}
</ul>

templates/theme0/mainapp/includes/inc-tab-content.html
{% load static i18n cache %}
<div class="tab-content featured-product__item">
    {% for prod in tab_content|slice:"4" %}
        <article class="tab-content__product">
            {% cache 120 tab_content prod.id %}
                <img class="tab-content__img" src="{{prod.pictures.all.0.image.url}}" alt="{% trans 'product' %}">
                <div class="tab-content_hidden">
                    {% include "mainapp/includes/snippets/inc-order.html" with bg=1 price=prod.pricelist.all.0.price prod=prod.id extra_cls="tab-content__button" %}
                    <h3 class="tab-content__h3">{% trans "Fishnet Chair" %}</h3>
                    <p class="text tab-content__text">{% blocktrans %}Seat and back with upholstery made of&nbsp;cold cure foam{% endblocktrans %}</p>
                </div>
            {% endcache %}
        </article>
    {% endfor %}
</div>

templates/theme0/mainapp/includes/inc_order_actions.html
{% load i18n %}
{% if object and object.status == object.FORMING %}
    <form method="post" action="{% url 'main:self_order_to_proc' object.pk %}">
        {% csrf_token %}
        <button class="btn btn-warning btn-round form-control last" type="submit">{% trans "Sent to proceed" %}</button>
    </form>
    <button class="btn btn-default btn-round form-control last">
    <a href="{% url 'main:self_order_delete' object.pk %}">{% trans "Delete" %}</a>
    </button>
{% endif %}
<button class="btn btn-info btn-round form-control last">
<a href="{% url 'main:self_order_list' %}">
    {% trans "To invoice list" %}
</a>
</button>
<button class="btn btn-default btn-round form-control last">
<a href="{% url 'main:home' %}">{% trans "Home" %}</a>
</button>

templates/theme0/mainapp/includes/inc_order_summary.html
{% load i18n %}
{% if object %}
    <div class="h2">{% trans "Invoice №" %}{{ object.pk }} от {{ object.date|date:"Y-m-d H:i:s" }}</div>
    <hr>
    <div class="h4">{% trans "customer" %}: {{ user.last_name }} {{ user.first_name }} </div>
    <div class="h4">{% trans "updated" %}: {{ object.date_modif|date:"Y-m-d H:i:s" }}</div>
    <div class="h4">{% trans "status" %}: {{ object.get_status_display }}</div>
    <hr>
    <div class="h4">
        {% trans "total quantity of goods" %}: <span class="order_total_quantity">{{ object.total_quant|floatformat }}</span>
    </div>
    <div class="h3">
        {% trans "total cost" %}: <span class="order_total_cost">{{ object.total_cost|floatformat }}</span> {% trans "sq" %}
    </div>
{% endif %}
<hr>